//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmanetKitaplar
    {
        public int ID { get; set; }
        public Nullable<int> KitapId { get; set; }
        public Nullable<int> KullaniciId { get; set; }
        public Nullable<System.DateTime> AldigiTarih { get; set; }
        public Nullable<System.DateTime> VerecegiTarih { get; set; }
        public Nullable<System.DateTime> VerdigiTarih { get; set; }
        public Nullable<decimal> Borcu { get; set; }
        public string HasarDurumu { get; set; }
        public Nullable<bool> TeslimDurumu { get; set; }
        public string HasarYeri { get; set; }
    
        public virtual Kitap Kitap { get; set; }
        public virtual Users Users { get; set; }
    }
}
