//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Kategori
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kategori()
        {
            this.KitapKategorileri = new HashSet<KitapKategorileri>();
        }
    
        public int ID { get; set; }
        [Range(000, 9999, ErrorMessage = "Dewey Kodu Doðru Deðil [0-9999]")]
        [Required(ErrorMessage = "Dewey Kodunu Giriniz")]
        public string DeweyId { get; set; }
        [StringLength(100, ErrorMessage = "Ýsim En Fazla 100 Karakter Olabilir")]
        [Required(ErrorMessage = "Kategori Adýný Giriniz")]
        public string Isim { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KitapKategorileri> KitapKategorileri { get; set; }
    }
}
